Add basic citus upgrade tests
citusdata/test-automation pull request #97
Opened 2019-09-09 12:45 UTC by SaitTalhaNisanci

This PR adds simple upgrade tests, it checks:
- Upgrading citus version is successful with server restart
- Upgrading citus version without restarting server forces you to restart server

To run the test run :
```
fab run.update
```

2019-10-03 17:45 UTC, hanefi requested changes
I did not test the changes here myself yet. Left some initial reviews. Looks good overall

2019-10-03 17:45 UTC, hanefi commented on fabfile/constants.py
> +ALTER_CITUS = 'ALTER EXTENSION citus UPDATE;'
If we do not provide `TO version` at the end, this will update to the latest version available. Is this really what we want?

2019-10-03 17:45 UTC, hanefi commented on fabfile/constants.py
> +ALTER_CITUS = 'ALTER EXTENSION citus UPDATE;'
and maybe have aline ending at the end as well

2019-10-03 17:45 UTC, hanefi commented on fabfile/run.py
> +     pg_version = '11.5'
similarly, instead of a hardcoded value, can this be a parameter as well?

2019-10-03 17:45 UTC, hanefi commented on fabfile/run.py
> +     pg_version = '11.5'
An alternative solution is to use `config.settings['pg-version']`
This way we can override this by adding some initial use commands. For example

	fab use.postgres:12.0 run.update:8.1:8.2

2019-10-10 08:07 UTC, SaitTalhaNisanci commented
@hanefi we know have citus upgrade tests in our CI, I think we can close this, I dont see any benefit of this PR now, what do you think?

2019-10-14 09:33 UTC, SaitTalhaNisanci commented
Closing this since we have these tests as part of our CI jobs now.

2019-10-14 09:33 UTC, closed without merging